version: '3.8'

services:
  api:
    build: .
    ports:
      - "8000:80"
    volumes:
      - .:/app
    depends_on:
      - db
    env_file:
      - .env

  db:
    image: postgres:13
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=n8n_workflows
    ports:
      - "5432:5432"

volumes:
  postgres_data: